### PR TITLE
Update cmake module files

### PR DESCRIPTION
**Pull request by chan-hoo**
The cmake module files 'FindESMF.cmake' and 'FindNetCDF.cmake' are updated with the latest version to fix the issue on compilation with hpc-stack.

### CODE REVIEW

**Comment by bbakernoaa** [comment]
Thanks @chan-hoo I'll take a look this afternoon.  I'm assuming this compiled and everything works.  Just want to make sure the outputs are the same with the old modules vs the new ones. A sanity check

**Comment by bbakernoaa** [comment]
@chan-hoo I was able to get this to run compile and have been able to confirm it produces bit for bit results with the previous modulefile.  We should update the module file in `NEXUS/modulefiles` as appropriate or make a reference to hoc-stack on each machine in case this built outside the workflow

**Comment by chan-hoo** [comment]
@bbakernoaa, Sure. I'll update them.

**Comment by chan-hoo** [comment]
@bbakernoaa, the module files are updated. I removed 'wcoss_cray' from the list.

**Comment by bbakernoaa** [comment]
Looks good @chan-hoo

**Pull request merged**
