### PR TITLE
Fixes to pretty step

### PR DESCRIPTION
**Pull request by zmoon**
Even with applying  `np.nan_to_num(x.filled(np.nan))` on the input data, the written output still contained those (default) fill values (at least in my testing). The way I found to get it to work properly is to copy the input to a temporary variable and then run `np.nan_to_num` on that. This increases the runtime slightly, but I decreased complevel which compensates [^a].

Also
* fixed the times (they were overly offset) and added some correctness checks
* cleaned up the CLI a bit

The original script takes ~ 23.5 s on Hera login node, this new one ~ 19.5 s. 

[^a]: Output file size only increases by a few MB, 534M -> 542M

### CODE REVIEW

**Comment by zmoon** [comment]
@bbakernoaa I kept the original version too but can remove if you want. Should work the same.

**Review by bbakernoaa — APPROVED** [review]

**Comment by bbakernoaa** [comment]
looks good to me

**Comment by zmoon** [comment]
do you want the old one removed?

**Comment by bbakernoaa** [comment]
Lets merge this

**Pull request merged**
