### PR TITLE
Commit of updated global HTAPv3 and CAMS-TEMPO

### PR DESCRIPTION
**Pull request by drnimbusrain**
These are feature updates to include updated global HTAPv3 2018 emissions as well as CAMS-TEMPO gridded weights on top of the updated NEI2019 config files.

### CODE REVIEW

**Review by bbakernoaa — APPROVED** [review]

**Comment by bbakernoaa** [comment]
Think we just need to fix the pre-commit and it should be good.

**Comment by drnimbusrain** [comment]
@bbakernoaa   Thank you! @zmoon Can you check this quickly, seems some linting for unknown reason.

**Comment by bbakernoaa** [comment]
It could be as simple as a space at the end of the line.


Barry Baker

National Oceanic and Atmospheric Administration
Air Resources Laboratory
Physical Research Scientist
Chemical Modeling and Emissions Group Leader
NCWCP, R/ARL, Rm. 4204
5830 University Research Court
College Park, Maryland  20740
Phone: ‪(301) 683-1395‬

**Comment by drnimbusrain** [comment]
@bbakernoaa @zmoon Are we ready to move this forward?

Here are preliminary results of the updated NEI2019 and Global updates on ozone and PM2.5
image

image

**Comment by bbakernoaa** [comment]
good to me.  @zmoon?

**Review by zmoon — APPROVED** [review]
LGTM

**Pull request merged**
