### PR TITLE
Fix cmake issue with Rocky8 on Hera

### PR DESCRIPTION
**Pull request by chan-hoo**
After Rocky8 transition on Hera, the nexus build fails in the develop branch of the UFS SRW App (SRW-AQM). This PR fixes this issue.

### CODE REVIEW

**Comment by chan-hoo** [comment]
@bbakernoaa, this is an urgent PR to fix the Rocky8 issue on Hera in SRW-AQM. Please review this PR as early as possible.

**Comment by bbakernoaa** [comment]
@zmoon this looks ok to me. Can you take a quick look?

**Review by zmoon — APPROVED** [review]
Fine with me. Confirmed it works as expected.

**Comment by bbakernoaa** [comment]
@chan-hoo merged

**Comment by chan-hoo** [comment]
Thanks!!

**Pull request merged**
