### PR TITLE
For GFS bio script, support non 3-hourly; concat pretty

### PR DESCRIPTION
**Pull request by zmoon**
The GFS bio script (preparing GFS data for input to NEXUS for generating biogenic emissions) has changed significantly.
* non-3-hourly GFS (e.g. hourly for NRT runs) now supported
  * Maybe hour-ceiling the first GFS time when computing the M2 times with arange would be enough to generalize beyond the current assumption of GFS times being on-the-hour, if necessary at some point
* no regridding, just the minimal adjustments needed in order to meet the COARDS conventions, improving spatial resolution for biogenic emissions calculations
  * previously we interpolated to the coarser GEOS-Chem MERRA-2 grid
* Output times are now on the hour instead of on the half hour (GEOS-Chem MERRA-2 files are on the half-hour)
  * thus, no time interp is done/needed if hourly GFS is used
* nc attrs and number format of the times now set to match GFS, with time calculations done in float instead of with datetime types

:point_up: These changes make this script run significantly faster.

So that we can more easily identify time overlaps in split runs, we now plan to run the concat script after the make-pretty script, and the concat script has been updated accordingly. When combining the splits, if there are duplicate times, the data from the later split file is used (e.g. if split 00 and 01 both have 2023-05-12 00:00, the data from split 01 is used).

### CODE REVIEW

**Comment by zmoon** [comment]
Originally was storing the intermediate calculation (regridding) in the output ds object, but hourly GFS has more times than the M2 times, so had to change that. With this, I found that the regridded data was originally the wrong shape (but nc4 I guess was automatically aligning the dims properly). With the new intermediate calc storage, had to reshape oppositely.

Short 3-hourly test:
```
./utils/python/nexus_gfs_bio.py -i /scratch1/NCEPDEV/stmp2/Barry.Baker/for_zach/gfs.t06z.sfcf00{0,3}.nc -o t.nc
```
Identical results, but this newer possibly a bit slower, maybe 28 vs 32 s on login node. Maybe could do just one variable loop so don't have to allocate as much.

**Comment by bbakernoaa** [comment]
Thanks @zmoon ill test this tomorrow morning

**Comment by bbakernoaa** [comment]
ok this did fix the assertion error but it doesn't seem to fix our problem.  I'm trying to setup something on hera to replicate the entire issue

**Comment by zmoon** [comment]
Too bad, thanks for the update

**Comment by bbakernoaa** [comment]
@zmoon @drnimbusrain 

I've been able to complete a few tests on HERA that show this problem.

workflow with the production/AQM.v7 branch: `/scratch2/NCEPDEV/naqfc/Barry.Baker/workfow/aqmprod-dev`
config.yaml: `/scratch2/NCEPDEV/naqfc/Barry.Baker/workfow/aqmprod-dev/ush/config.yaml`
run directory: `/scratch2/NCEPDEV/stmp3/Barry.Baker/expt_dirs/biodiag`

I've also run a few tests that show it in the aqm.t12z.NEXUS* file

- File using retro **3hourly**: `/scratch2/NCEPDEV/stmp3/Barry.Baker/expt_dirs/biodiag/2023051112/NEXUS/aqm.t12z.NEXUS_Expt_split.00.nc.backup`
- Using **hourly** inputs from the previous cycle: `/scratch2/NCEPDEV/stmp3/Barry.Baker/expt_dirs/biodiag/2023051112/NEXUS/aqm.t12z.NEXUS_Expt_split.00.nc.backup2`
- using **latest** develop branch of nexus (with fix/gfs_bio merged in): `/scratch2/NCEPDEV/stmp3/Barry.Baker/expt_dirs/biodiag/2023051112/NEXUS/aqm.t12z.NEXUS_Expt_split.00.nc`


So far it looks like the 3 hourly looks the best but there is still a larger jump between 12 hour forecast and 13 hour forecast in the 3hourly 

12hour - **3hourly**: 
image

13hour - **3hourly**:
image

=================================================================

11hour - **hourly**:
image

12hour - **hourly**:
image

13hour - **hourly**:
image


==================================================================

the latest develop branch looks the same as the **hourly** run

**Comment by bbakernoaa** [comment]
@zmoon @rmontuoro 

I did a 4th run using the MERRA2 inputs from 2019. I'm not seeing the issue pop up.

11 hours in 
image


12 hours in 
image


13 hours in 
image

**Comment by zmoon** [comment]
> the latest develop branch looks the same as the hourly run

This is confusing to me, since without the fix in this branch, we confirmed that for an hourly GFS case the bio inputs were not properly prepared, failing before the time interp step. But I guess they would be pretty similar, just half hour off.

**Comment by drnimbusrain** [comment]
@bbakernoaa @zmoon

Indeed this is confusing, but to me it seems like a radiation issue in the way the biogenic emissions go to zero  over CONUS (but not necessarily over AK and HI) at 11 UTC and then reappear at 12 UTC.  The pattern of PARDR is very erratic between hours (seems to skip unnaturally ahead every 6 hour interval) and also has a very blocky spatial pattern for the input file _/scratch2/NCEPDEV/stmp3/Barry.Baker/expt_dirs/biodiag/2023051112/tmp_NEXUS_EMISSION_00/GFS_SFC_MEGAN_INPUT.nc_, 

MEGAN_GFS_PARDR_20230511


Or, maybe this is just a GFS initialization impact?

This may have an impact on the temporal/spatial patterns of the biogenic emissions, with similar strange features.  Note that the biogenic emissions drop out over CONUS at hour 36 too in your test runs.  Something seems in error here.  This is not seen in the T2M variable though.  

Also, not to bring up another issue here, but we have also noticed in the "phy" output from Online-CMAQ a similar choppy pattern in the downward radiation variables, e.g.,:

image

This temporal/spatial pattern may be a larger issue in UFS-SRW-App?

**Comment by bbakernoaa** [comment]
Noticed the jump too. This is actually in the GFS data itself. I’m going to reach out to EMC to figure out what is happening

**Comment by drnimbusrain** [comment]
@bbakernoaa Yes, that is what I thought, and can see weird patterns in the GFS data in the 'phy' file's radiation data...

**Comment by bbakernoaa** [comment]
@yangfanglin @rmontuoro @JianpingHuang-NOAA 

We are noticing these weird jumps in the radiation (particularly the `vddsf_ave` and `vbdsf_ave` variables) from the operational GFS files.  Could you help with understanding what is happening here. It is causing some confusion diagnosing some issues with the biogenic emissions for the AQMv7 implementaiton.  Please see above and https://github.com/ufs-community/ufs-srweather-app/issues/791

**Comment by yangfanglin** [comment]
@bbakernoaa Barry,  did not see any plots in https://github.com/ufs-community/ufs-srweather-app/issues/791.  My guess is that GFS accumulated fields all use a 6-hour bucket.   So at FH3 the average value is for 0-3 hour,  at FH06 for 0-6 hour, at FH09 for 6-9 hour.   Conversions is required if you need all 3-hr mean fluxes.   For instance, at FH12, you can get the 9-12hr mean flux using  (F12 x 6 - F9 x3)/3.     If you need to get hourly fluxes, the conversion should be changed.  For instance,   Hourly mean flux at FH12 should be computed as (F12 x 6 -F11 x 5),  and at FH13 is simply the F13.

**Review by bbakernoaa — COMMENTED** [review]
Can we replace the concatenate_nexus_post_split.py file with this instead of duplicating with a different name?

**Comment by bbakernoaa** [comment]
@zmoon  the current changes seem to work well

**Comment by yangfanglin** [comment]
@bbakernoaa Had the weird jumps in the radiation been resolved ?

**Comment by bbakernoaa** [comment]
@yangfanglin Yes the weird jumps have been resolved.  Packaging it up now so that the test @JianpingHuang-NOAA can be do a test of it.

**Review by bbakernoaa — APPROVED** [review]

**Pull request merged**
